// ── Inline style helpers using CSS vars ────────────────────────────────────
// All values reference design-system tokens defined in index.css.
// Add new shared styles here; avoid ad-hoc style objects in components.
export const s = {
    pageWrap: {
        minHeight: '100vh',
        background: 'linear-gradient(145deg, var(--bg-base) 0%, var(--bg-mid) 100%)',
        padding: '2rem 2.5rem',
        fontFamily: "'Inter', sans-serif",
        transition: 'background 0.4s ease',
    },
    card: {
        background: 'var(--bg-surface-alt)',
        border: '1px solid var(--border)',
        borderRadius: '1.25rem',
        padding: '1.75rem 2rem',
        marginBottom: '1.1rem',
        boxShadow: '0 2px 12px rgba(0,0,0,0.04)',
        transition: 'background 0.4s, border-color 0.4s',
    },
    cardAlt: {
        background: 'var(--bg-surface)',
        border: '1px solid var(--border)',
        borderRadius: '1.25rem',
        padding: '1.75rem 2rem',
        marginBottom: '1.1rem',
        boxShadow: '0 2px 12px rgba(0,0,0,0.04)',
        transition: 'background 0.4s, border-color 0.4s',
    },
    heading: {
        fontFamily: "'Cormorant Garamond', serif",
        fontSize: '2.6rem',
        fontWeight: 500,
        color: 'var(--text-head)',
        letterSpacing: '-0.01em',
        lineHeight: 1.15,
        margin: 0,
    },
    subheading: {
        fontFamily: "'Cormorant Garamond', serif",
        fontSize: '1.3rem',
        fontWeight: 500,
        color: 'var(--text-head)',
        margin: '0 0 0.5rem 0',
    },
    label: {
        display: 'block',
        fontSize: '0.72rem',
        fontWeight: 700,
        letterSpacing: '0.09em',
        textTransform: 'uppercase' as const,
        color: 'var(--text-muted)',
        marginBottom: '0.5rem',
    },
    btn: {
        background: 'var(--accent)',
        color: '#fff',
        border: 'none',
        borderRadius: '0.75rem',
        padding: '0.85rem 1.5rem',
        fontSize: '0.9rem',
        fontWeight: 600,
        cursor: 'pointer',
        transition: 'background 0.2s',
        fontFamily: "'Inter', sans-serif",
        letterSpacing: '0.02em',
    },
    btnGhost: {
        background: 'var(--accent-light)',
        color: 'var(--accent)',
        border: '1px solid var(--border)',
        borderRadius: '0.625rem',
        padding: '0.45rem 0.9rem',
        fontSize: '0.78rem',
        fontWeight: 600,
        cursor: 'pointer',
        transition: 'background 0.2s',
        fontFamily: "'Inter', sans-serif",
    },
    btnFile: {
        background: 'var(--bg-surface)',
        color: 'var(--accent)',
        border: '1px solid var(--border)',
        borderRadius: '0.625rem',
        padding: '0.6rem 1rem',
        fontSize: '0.82rem',
        fontWeight: 600,
        cursor: 'pointer',
        transition: 'background 0.2s',
        fontFamily: "'Inter', sans-serif",
        textAlign: 'left' as const,
    },
    btnLoaded: {
        background: 'var(--accent-light)',
        color: 'var(--accent)',
        border: '1px solid var(--border)',
        borderRadius: '0.625rem',
        padding: '0.6rem 1rem',
        fontSize: '0.82rem',
        fontWeight: 600,
        cursor: 'pointer',
        transition: 'background 0.2s',
        fontFamily: "'Inter', sans-serif",
        textAlign: 'left' as const,
    },
    select: {
        width: '100%',
        padding: '0.65rem 2.5rem 0.65rem 1rem',
        border: '1px solid var(--border)',
        borderRadius: '0.75rem',
        background: 'var(--bg-surface-alt)',
        color: 'var(--text-body)',
        fontSize: '0.9rem',
        outline: 'none',
        fontFamily: "'Inter', sans-serif",
        cursor: 'pointer',
        appearance: 'none' as const,
        backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%23888' d='M6 8L1 3h10z'/%3E%3C/svg%3E")`,
        backgroundRepeat: 'no-repeat',
        backgroundPosition: 'right 0.9rem center',
    },
    tag: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.25rem',
        background: 'var(--tag-bg)',
        color: 'var(--tag-text)',
        borderRadius: '999px',
        padding: '0.2rem 0.65rem',
        fontSize: '0.75rem',
        fontWeight: 500,
    },
    inputStyle: {
        border: '1px solid var(--border)',
        borderRadius: '0.5rem',
        background: 'var(--bg-surface)',
        color: 'var(--text-body)',
        fontSize: '0.85rem',
        outline: 'none',
        fontFamily: "'Inter', sans-serif",
    },
    divider: {
        border: 'none',
        borderTop: '1px solid var(--border)',
        margin: '1.25rem 0',
    },
};
